spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
inventory:
  url: http://localhost:8082
